# Generated by Django 5.0.6 on 2024-07-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
